# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: couplage2

on:
  push:
    branches: [ master ]
    paths:
      - 'examples/mod1D/couplage2.py'
  pull_request:
    branches: [ master ]
    paths:
      - 'examples/mod1D/couplage2.py'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install numpy scipy matplotlib ipython jupyter pandas sympy nose
        python setup.py develop
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: couplage.py run
      run: |
        cd examples/mod1D
        python couplage2.py True 0 "couplage2_SummerProdECS"
        python couplage2.py False 0 "couplage2 SummerProd"
        python couplage2.py True 1 "couplage2_SummerProdChauffageECS"
        python couplage2.py False 1 "couplage2_SummerProdChauffage"
        python couplage2.py True 2 "couplage2_AllYearProdChauffageECS"
        python couplage2.py False 2 "couplage2_AllYearProdChauffage"
        python couplage2.py True 3 "couplage2_ProdIfRayAbove250ChauffageECS"
        python couplage2.py False 3 "couplage2_ProdIfRayAbove250Chauffage"
        mkdir figures
        mv *.png figures/
    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: figures
        path: 'examples/mod1D/figures'
